### ISSUE TITLE
initDatabases.js  not creating mongo database

### ISSUE THREAD

**Issue by ZergRushJoe** [ZergRushJoe/databaseExp#1]
can someone fix my code for the initDatabases.js

**Comment by knhumbarger** [comment]
initDatabases.js is not creating the mongo database because the mongo service must be already installed on your machine and running on the specified port. 

**To install Mongo:**

-Download Link (I installed default option): https://www.mongodb.com/download-center#community

-Step-by-step instructions: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/

I am currently working to automate the startup of the mongo service so that we will not have to start it manually each time.
